version: "3.7"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      # listen address of HTTP server inside container
      SCORE_LISTEN: 0.0.0.0:80
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./score.sqlite:/app/score.sqlite
